---
title: "Individual Project"
output: html_document
date: '2023-11-06'
---
```{r}
library(car)
library(carData)
library(leaps)
```


Read the data
```{r}
setwd("C:\\Users\\ned20\\Documents\\GitHub\\STAT-429-Individual-Project")
lifeExpectData<-read.table("Life Expectancy Data.csv", header=TRUE,sep = ",")


```


Remove some of the irrelavent predictorts
```{r}
lifeExpectData2 <- lifeExpectData[,!(names(lifeExpectData) %in% c("Country","Year", "thinness..1.19.years", "thinness.5.9.years", "Income.composition.of.resources", "Total.expenditure", "Diphtheria", "percentage.expenditure", "under.five.deaths"))]

clean_data <- na.omit(lifeExpectData2)
clean_data <- clean_data[clean_data$GDP != 0, ]

clean_data$Status_Dummy <- factor(clean_data$Status, levels = c("Developing", "Developed"), labels = c(0, 1))


```

 v 
```{r}
boxplot(clean_data$Life.expectancy,main="Life Expectancy",col="cornflowerblue")

barplot(table(clean_data$Status_Dummy), main="Country Status",
   xlab="0 -> Developing Country, 1 -> Developed")

boxplot(clean_data$infant.deaths,main="Infant Deaths",col="cornflowerblue")

boxplot(clean_data$Adult.Mortality,main="Adult Mortality",col="cornflowerblue")

boxplot(clean_data$Measles,main="Measle",col="cornflowerblue")

boxplot(clean_data$Polio,main="Polio",col="cornflowerblue")

boxplot(clean_data$GDP,main="GDP",col="cornflowerblue")

boxplot(clean_data$GDP,main="Schooling",col="cornflowerblue")

pairs(Life.expectancy ~ Status_Dummy + infant.deaths + Adult.Mortality + Measles + Polio + GDP + Schooling, data = clean_data,lower.panel=NULL)


```


Model 1:
```{r}
model1 <- lm(Life.expectancy ~ Status_Dummy + infant.deaths + Adult.Mortality + Measles + Polio + GDP + Schooling, data = clean_data)

summary(model1)
```

```{r}
par(mfrow=c(2,2))
plot(model1)
```

```{r}
plot(model1$fitted.values,rstandard(model1),xlab="Fitted values",
ylab="Standardized residuals")
abline(h=3,lty=2,col=6,lwd=2)
abline(h=-3,lty=2,col=6,lwd=2)
identify(model1$fitted.values,rstandard(model1))

```

```{r}
mmps(model1)
```

```{r}

summary(powerTransform(cbind(Life.expectancy , Adult.Mortality , Polio , GDP , Schooling)~1,clean_data))
```


```{r}

clean_data$NewPolio <- clean_data$Polio ^ 3.09
clean_data$NewGDP <- clean_data$GDP ^ 0.09
clean_data$NewLife.expectancy <- clean_data$Life.expectancy ^ 2.87

model2 <- lm(NewLife.expectancy ~ Status_Dummy + infant.deaths + Adult.Mortality + Measles + NewPolio + NewGDP + Schooling, data = clean_data)
summary(model2)

```
```{r}
par(mfrow=c(2,2))
plot(model2)

```


```{r}
plot(model2$fitted.values,rstandard(model2),xlab="Fitted values",
ylab="Standardized residuals")
abline(h=3,lty=2,col=6,lwd=2)
abline(h=-3,lty=2,col=6,lwd=2)
identify(model2$fitted.values,rstandard(model2))

```

```{r}
mmps(model2)
```






```{r}

variableSelection <-regsubsets(NewLife.expectancy ~ Status_Dummy + infant.deaths + Adult.Mortality + Measles + NewPolio + NewGDP + Schooling, data = clean_data)

selectionSummary <- summary(variableSelection)

selectionSummary
```


```{r}
par(mfrow=c(2,2))
plot(selectionSummary$rss,xlab="Number of varialbes",ylab="SSE",type="l")
points(which.min(selectionSummary$rss),selectionSummary$rss[which.min(selectionSummary$rss)],col="red",cex=2,pch=20)

plot(selectionSummary$adjr2,xlab="Number of variables",ylab="Adjusted R^2",type="l")
points(which.max(selectionSummary$adjr2),selectionSummary$adjr2[which.max(selectionSummary$adjr2)],col="red",cex=2,pch=20)

plot(selectionSummary$bic,xlab="Number of variables",ylab="BIC",type="l")
points(which.min(selectionSummary$bic),selectionSummary$bic[which.min(selectionSummary$bic)],col="red",cex=2,pch=20)

plot(selectionSummary$cp,xlab="Number of variables",ylab="Cp",type="l")
points(which.min(selectionSummary$cp),selectionSummary$cp[which.min(selectionSummary$cp)],col="red",cex=2,pch=20)


```

```{r}

model3 <- lm(NewLife.expectancy ~ Status_Dummy + Adult.Mortality + NewPolio + NewGDP + Schooling, data = clean_data)
summary(model3)
```

```{r}

par(mfrow=c(2,2))
plot(model3)

```
```{r}
mmps(model3)

```


```{r}
plot(model3$fitted.values,rstandard(model3),xlab="Fitted values",
ylab="Standardized residuals")
abline(h=3,lty=2,col=6,lwd=2)
abline(h=-3,lty=2,col=6,lwd=2)
identify(model3$fitted.values,rstandard(model3))

```


```{r}

anova(model3, model2)

```

```{r}
vif(model3)
```

```{r}
shapiro.test(model3$residuals)
```